### ISSUE TITLE
Compatibility with Arduino Uno

### ISSUE THREAD

**Issue by topazwishes** [RollingGecko/VescUartControl#19]
Is there any way to get this to work on Arduino Uno? I don't have a Mega or Nano.

Have been trying to edit the code to make it compatible for Uno but it doesn't seem to work.

**Comment by RollingGecko** [comment]
Hi,

It is no problem to run it on the uno. It has the same chip as the nano (328p). Maybe you have to change only pin settings. Mega is only usefull for debugging.
Note that there are still some problems with the new VESC FW and this library. Take a look to the other issues. But I discontinued this project because I have now time for. So everybody is welcoem to continue it.

Cheers 
Andy
