### ISSUE TITLE
Message Handler for >256 byte payload length

### ISSUE THREAD

**Issue by KnechtRuprecht** [RollingGecko/VescUartControl#3]
Hello,

Is it possible to include the VESC command "COMM_GET_MCCONF"? I tried it myself but get stuck at the comamnd "//ToDo: Add Message Handling > 255 (starting with 3)" from your "switch (messageReceived[0])".

Thank you very much.

**Comment by RollingGecko** [comment]
In general that could be done. At the moment that would not make sense due to the fact that either the nrf24L01 chip as well as bluetooth ble can handle that big data packages. Also for the implementation of ble and the wish of doing configuration as well over that interface, we need new messages also on the VESC that are limited in package size. Also it must been checked once again if on the ble specification the limitation is even smaller than 255.
So this request is limited only to UART communication and by that fact will not be considered at the moment because there is a more appropriate workaround shown above. By the way the creation of a own message isn't that complicate. In the easiest way you can split e.g. COMM_GET_MCCONF into half.
